all:
	clear
	g++ 1003.cpp -o a.out -std=c++11 -lm -Wall -O2
	clear
	cat input.txt | ./a.out
diff:
	clear
	g++ 1003.cpp -o a.out -std=c++11 -lm -Wall -O2
	clear
	cat input.txt | ./a.out > output.txt
	clear
	diff output.txt ans.txt
